<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\MarketEye.Domain\MarketEye.Domain.csproj" />
    <ProjectReference Include="..\..\src\MarketEye.Application\MarketEye.Application.csproj" />
    <ProjectReference Include="..\..\src\MarketEye.Infrastructure\MarketEye.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\MarketEye.Ai\MarketEye.Ai.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

</Project>
